# Generated by Django 5.0.7 on 2026-06-24 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_score', models.FloatField(default=10.0)),
                ('weight', models.FloatField(default=1.0)),
                ('parent_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tiêu chí đánh giá',
                'db_table': 'evaluation_criterias',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Nháp'), (1, 'Đang thực hiện'), (2, 'Hoàn thành')], default=0)),
                ('department_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Đợt đánh giá',
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='RatingAwardTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=100)),
            ],
            options={
                'verbose_name': 'Danh hiệu',
                'db_table': 'rating_award_titles',
            },
        ),
        migrations.CreateModel(
            name='RatingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(blank=True, null=True)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ratings.rating')),
            ],
            options={
                'db_table': 'rating_participants',
                'unique_together': {('rating', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='RatingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('score', models.FloatField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('rated_by', models.UUIDField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.evaluationcriteria')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.ratingparticipant')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ratings.rating')),
            ],
            options={
                'db_table': 'rating_results',
                'unique_together': {('rating', 'participant', 'criteria', 'rated_by')},
            },
        ),
    ]
