# Generated by Django 5.2.15 on 2026-07-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationcriteria',
            options={
                'verbose_name': 'Tiêu chí đánh giá',
                'verbose_name_plural': 'Tiêu chí đánh giá',
            },
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={
                'verbose_name': 'Đợt đánh giá',
                'verbose_name_plural': 'Đợt đánh giá',
            },
        ),
        migrations.AlterModelOptions(
            name='ratingawardtitle',
            options={
                'verbose_name': 'Danh hiệu',
                'verbose_name_plural': 'Danh hiệu',
            },
        ),
    ]
