# Generated by Codex on 2026-06-26

import django.db.models.deletion
from django.db import migrations, models


def backfill_staff_files(apps, schema_editor):
    StaffFile = apps.get_model('accounts', 'StaffFile')
    Staff = apps.get_model('departments', 'Staff')

    # Previous target used 1/2/3. 185 uses 0/1/2.
    if StaffFile.objects.filter(type_file=3).exists() and not StaffFile.objects.filter(type_file=0).exists():
        StaffFile.objects.filter(type_file=1).update(type_file=0)
        StaffFile.objects.filter(type_file=2).update(type_file=1)
        StaffFile.objects.filter(type_file=3).update(type_file=2)

    staff_by_user_id = {
        str(staff.user_id): staff.id
        for staff in Staff.objects.filter(user_id__isnull=False)
    }
    for staff_file in StaffFile.objects.filter(staff_id__isnull=True):
        staff_id = staff_by_user_id.get(str(staff_file.user_id)) if staff_file.user_id else None
        if staff_id:
            staff_file.staff_id = staff_id
            staff_file.save(update_fields=['staff'])


def reverse_type_file_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_staff_185_profile'),
        ('accounts', '0002_185_reference_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafffile',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='departments.staff'),
        ),
        migrations.AlterField(
            model_name='stafffile',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.RunPython(backfill_staff_files, reverse_type_file_noop),
        migrations.AddIndex(
            model_name='stafffile',
            index=models.Index(fields=['staff', 'type_file', 'is_deleted'], name='staff_files_staff_i_c4e63d_idx'),
        ),
        migrations.AddIndex(
            model_name='stafffile',
            index=models.Index(fields=['user_id', 'type_file', 'is_deleted'], name='staff_files_user_id_6c9a21_idx'),
        ),
        migrations.AlterModelOptions(
            name='stafffile',
            options={'verbose_name': 'File nhân sự', 'verbose_name_plural': 'File nhân sự'},
        ),
        migrations.AlterModelOptions(
            name='userconcurrently',
            options={'verbose_name': 'Chức vụ kiêm nhiệm', 'verbose_name_plural': 'Chức vụ kiêm nhiệm'},
        ),
    ]