# Generated by Django 5.2.15 on 2026-06-30 02:54

import django.db.models.deletion
import uuid
from django.db import migrations, models

def copy_legacy_calendar_fields(apps, schema_editor):
    Calendar = apps.get_model('calendars', 'Calendar')
    CalendarJoin = apps.get_model('calendars', 'CalendarJoin')

    for item in Calendar.objects.all().iterator():
        Calendar.objects.filter(pk=item.pk).update(
            name=item.name or item.title,
            from_time=item.from_time or item.start_time,
            to_time=item.to_time or item.end_time,
            type=item.type if item.type is not None else item.calendar_type,
            place=item.place or item.location,
            join_type=item.join_type if item.join_type is not None else 0,
        )

    for item in CalendarJoin.objects.all().iterator():
        CalendarJoin.objects.filter(pk=item.pk).update(
            accept_type=item.accept_type if item.accept_type is not None else item.status,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='cancel_undo_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='from_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendar',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendar',
            name='join_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Phòng ban'), (1, 'Người dùng'), (2, 'Cá nhân')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='place',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='to_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Cuộc họp'), (1, 'Công tác'), (2, 'Khác')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarjoin',
            name='accept_dated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarjoin',
            name='accept_type',
            field=models.IntegerField(choices=[(0, 'Chờ xác nhận'), (1, 'Chấp nhận'), (2, 'Từ chối')], default=0),
        ),
        migrations.AddField(
            model_name='calendarjoin',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarjoin',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarjoin',
            name='department_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarjoin',
            name='refuse_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarjoin',
            name='refuse_dated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarjoin',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(copy_legacy_calendar_fields, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CalendarFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('file', models.CharField(blank=True, max_length=1000, null=True)),
                ('extension', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Hệ thống'), (1, 'Chia sẻ')], null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='calendars.calendar')),
            ],
            options={
                'db_table': 'calendar_files',
            },
        ),
        migrations.CreateModel(
            name='CalendarJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('deadline', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Canceled'), (2, 'Finished')], default=0)),
                ('type', models.IntegerField(choices=[(0, 'Tự động từ chối'), (1, 'Khóa sau ngày kết thúc'), (2, 'Thông báo sắp đến'), (3, 'Thông báo bắt đầu'), (4, 'Khóa sau khi kết thúc')], default=2)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='calendars.calendar')),
            ],
            options={
                'db_table': 'calendar_jobs',
            },
        ),
    ]

