# Generated by Django 5.2.15 on 2026-06-30 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_calendar_cancel_reason_calendar_cancel_undo_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarfile',
            options={'verbose_name': 'Tệp đính kèm lịch', 'verbose_name_plural': 'Tệp đính kèm lịch'},
        ),
        migrations.AlterModelOptions(
            name='calendarjob',
            options={'verbose_name': 'Tác vụ lịch', 'verbose_name_plural': 'Tác vụ lịch'},
        ),
        migrations.AlterModelOptions(
            name='calendarjoin',
            options={'verbose_name': 'Người tham gia lịch', 'verbose_name_plural': 'Người tham gia lịch'},
        ),
        migrations.AlterField(
            model_name='calendar',
            name='calendar_type',
            field=models.IntegerField(choices=[(0, 'Họp'), (1, 'Sự kiện'), (2, 'Nhắc nhở'), (3, 'Công việc')], default=0, verbose_name='Loại lịch'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do hủy'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='cancel_undo_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày khôi phục hủy'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Màu sắc'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Người xóa'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='department_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='end_time',
            field=models.DateTimeField(verbose_name='Thời gian kết thúc'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='from_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Bắt đầu'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='is_all_day',
            field=models.BooleanField(default=False, verbose_name='Cả ngày'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Đã hủy'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Đã khóa'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='join_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Phòng ban'), (1, 'Người dùng'), (2, 'Cá nhân')], db_index=True, null=True, verbose_name='Phạm vi tham gia'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Đường dẫn'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa điểm'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Tên lịch'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='place',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa điểm'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start_time',
            field=models.DateTimeField(db_index=True, verbose_name='Thời gian bắt đầu'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='status',
            field=models.IntegerField(choices=[(0, 'Chờ xác nhận'), (1, 'Đã xác nhận'), (2, 'Đã hủy'), (3, 'Hoàn thành')], default=0, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='to_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Kết thúc'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Cuộc họp'), (1, 'Công tác'), (2, 'Khác')], db_index=True, null=True, verbose_name='Loại sự kiện'),
        ),
        migrations.AlterField(
            model_name='calendarfile',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='calendars.calendar', verbose_name='Lịch'),
        ),
        migrations.AlterField(
            model_name='calendarfile',
            name='extension',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Định dạng'),
        ),
        migrations.AlterField(
            model_name='calendarfile',
            name='file',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Tệp'),
        ),
        migrations.AlterField(
            model_name='calendarfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tên tệp'),
        ),
        migrations.AlterField(
            model_name='calendarfile',
            name='size',
            field=models.FloatField(blank=True, null=True, verbose_name='Dung lượng'),
        ),
        migrations.AlterField(
            model_name='calendarfile',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Hệ thống'), (1, 'Chia sẻ')], null=True, verbose_name='Loại tệp'),
        ),
        migrations.AlterField(
            model_name='calendarjob',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='calendars.calendar', verbose_name='Lịch'),
        ),
        migrations.AlterField(
            model_name='calendarjob',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='calendarjob',
            name='deadline',
            field=models.DateTimeField(verbose_name='Hạn xử lý'),
        ),
        migrations.AlterField(
            model_name='calendarjob',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Mã tác vụ'),
        ),
        migrations.AlterField(
            model_name='calendarjob',
            name='status',
            field=models.IntegerField(choices=[(0, 'Đang hoạt động'), (1, 'Đã hủy'), (2, 'Hoàn thành')], default=0, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='calendarjob',
            name='type',
            field=models.IntegerField(choices=[(0, 'Tự động từ chối người chưa xác nhận'), (1, 'Khóa lịch sau ngày kết thúc'), (2, 'Thông báo lịch sắp đến'), (3, 'Thông báo lịch bắt đầu'), (4, 'Khóa lịch sau khi kết thúc')], default=2, verbose_name='Loại tác vụ'),
        ),
        migrations.AlterField(
            model_name='calendarjoin',
            name='accept_dated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày chấp nhận'),
        ),
        migrations.AlterField(
            model_name='calendarjoin',
            name='accept_type',
            field=models.IntegerField(choices=[(0, 'Chờ xác nhận'), (1, 'Chấp nhận'), (2, 'Từ chối')], default=0, verbose_name='Trạng thái tham gia'),
        ),
        migrations.AlterField(
            model_name='calendarjoin',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='calendars.calendar', verbose_name='Lịch'),
        ),
        migrations.AlterField(
            model_name='calendarjoin',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Người xóa'),
        ),
        migrations.AlterField(
            model_name='calendarjoin',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa'),
        ),
        migrations.AlterField(
            model_name='calendarjoin',
            name='department_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='calendarjoin',
            name='refuse_content',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung từ chối'),
        ),
        migrations.AlterField(
            model_name='calendarjoin',
            name='refuse_dated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày từ chối'),
        ),
        migrations.AlterField(
            model_name='calendarjoin',
            name='status',
            field=models.IntegerField(choices=[(0, 'Chờ xác nhận'), (1, 'Chấp nhận'), (2, 'Từ chối')], default=0, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='calendarjoin',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Người dùng'),
        ),
    ]
