# Generated by Codex on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_aidi', '0013_merge_20260703_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedchat',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
