# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_staff_185_profile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['user', 'is_deleted'], name='staffs_user_id_290caf_idx'),
        ),
    ]