# Generated by Django 4.2.17 on 2026-07-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_aidi', '0012_delete_legacy_chat_note'),
        ('legacy_aidi', '0012_managed_chat_await_confirm'),
    ]

    operations = [
    ]
