# Generated by Django 5.0.7 on 2026-06-24 04:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('department_id', models.UUIDField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hồ sơ lưu trữ',
                'verbose_name_plural': 'Hồ sơ lưu trữ',
                'db_table': 'archives',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
