name: Check EoH Rule

on: [pull_request]

jobs:
  branch-name:
    runs-on: ubuntu-latest
    container: python:3.12-slim-bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Check branch name
        run: |
          cd .github
          python -m scripts.check_branch_name ${{ github.head_ref }}

  models-import:
    runs-on: ubuntu-latest
    container: python:3.12-slim-bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Check models importing
        run: |
          cd .github
          python -m scripts.check_models_are_imported_correctly

  tasks-import:
    runs-on: ubuntu-latest
    container: python:3.12-slim-bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Check tasks importing
        run: |
          cd .github
          python -m scripts.check_tasks_are_imported_correctly
