# Generated by Django 5.2.15 on 2026-06-24 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tổ chức',
                'verbose_name_plural': 'Tổ chức',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tỉnh/Thành phố',
                'verbose_name_plural': 'Tỉnh/Thành phố',
                'db_table': 'provinces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.CharField(db_index=True, max_length=36)),
                ('file', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('size', models.FloatField(default=0)),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.IntegerField(default=0)),
                ('type_file', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'File nhân sự',
                'verbose_name_plural': 'File nhân sự',
                'db_table': 'staff_files',
            },
        ),
        migrations.CreateModel(
            name='UserConcurrently',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.CharField(db_index=True, max_length=36)),
                ('role_id', models.CharField(blank=True, max_length=36, null=True)),
                ('department_id', models.CharField(blank=True, max_length=36, null=True)),
                ('organization_id', models.CharField(blank=True, max_length=36, null=True)),
            ],
            options={
                'verbose_name': 'Chức vụ kiêm nhiệm',
                'verbose_name_plural': 'Chức vụ kiêm nhiệm',
                'db_table': 'user_concurrentlies',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='accounts.province')),
            ],
            options={
                'verbose_name': 'Quận/Huyện',
                'verbose_name_plural': 'Quận/Huyện',
                'db_table': 'districts',
                'ordering': ['name'],
            },
        ),
    ]
