# Generated by Codex on 2026-06-26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def clean_user_concurrently_refs(apps, schema_editor):
    UserConcurrently = apps.get_model('accounts', 'UserConcurrently')
    User = apps.get_model('authentication', 'User')
    Role = apps.get_model('authentication', 'Role')
    Department = apps.get_model('departments', 'Department')
    Organization = apps.get_model('accounts', 'Organization')

    valid_users = {str(v) for v in User.objects.values_list('id', flat=True)}
    valid_roles = {str(v) for v in Role.objects.values_list('id', flat=True)}
    valid_departments = {str(v) for v in Department.objects.values_list('id', flat=True)}
    valid_organizations = {str(v) for v in Organization.objects.values_list('id', flat=True)}

    for item in UserConcurrently.objects.all():
        changed = False
        if item.user_id and str(item.user_id) not in valid_users:
            item.user_id = None
            changed = True
        if item.role_id and str(item.role_id) not in valid_roles:
            item.role_id = None
            changed = True
        if item.department_id and str(item.department_id) not in valid_departments:
            item.department_id = None
            changed = True
        if item.organization_id and str(item.organization_id) not in valid_organizations:
            item.organization_id = None
            changed = True
        if changed:
            item.save(update_fields=['user_id', 'role_id', 'department_id', 'organization_id'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_role_185_fields_roledepartment'),
        ('departments', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='district',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='accounts.district')),
            ],
            options={
                'verbose_name': 'Phường/Xã',
                'verbose_name_plural': 'Phường/Xã',
                'db_table': 'wards',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(clean_user_concurrently_refs, migrations.RunPython.noop),
        migrations.RunSQL(
            sql="""
            DO $$
            DECLARE idx record;
            BEGIN
                FOR idx IN
                    SELECT indexname
                    FROM pg_indexes
                    WHERE schemaname = current_schema()
                      AND tablename = 'user_concurrentlies'
                      AND indexname NOT LIKE '%pkey'
                      AND (
                          indexdef LIKE '%user_id%'
                          OR indexdef LIKE '%role_id%'
                          OR indexdef LIKE '%department_id%'
                          OR indexdef LIKE '%organization_id%'
                      )
                LOOP
                    EXECUTE format('DROP INDEX IF EXISTS %I.%I', current_schema(), idx.indexname);
                END LOOP;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RenameField(
            model_name='userconcurrently',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userconcurrently',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='userconcurrently',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='userconcurrently',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='userconcurrently',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concurrent_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userconcurrently',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_concurrentlies', to='authentication.role'),
        ),
        migrations.AlterField(
            model_name='userconcurrently',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_concurrentlies', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='userconcurrently',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_concurrentlies', to='accounts.organization'),
        ),
        migrations.AddIndex(
            model_name='userconcurrently',
            index=models.Index(fields=['user', 'is_deleted'], name='user_concu_user_id_bf9a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='userconcurrently',
            index=models.Index(fields=['role', 'department'], name='user_concu_role_id_38c54c_idx'),
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Tổ chức', 'verbose_name_plural': 'Tổ chức'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name'], 'verbose_name': 'Tỉnh/Thành phố', 'verbose_name_plural': 'Tỉnh/Thành phố'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name'], 'verbose_name': 'Quận/Huyện', 'verbose_name_plural': 'Quận/Huyện'},
        ),
    ]