# Generated by Django 5.2.15 on 2026-06-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_current_vn_admin_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name'], 'verbose_name': 'Cấp huyện cũ (lưu trữ)', 'verbose_name_plural': 'Cấp huyện cũ (lưu trữ)'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name'], 'verbose_name': 'Tỉnh/Thành phố trực thuộc TW', 'verbose_name_plural': 'Tỉnh/Thành phố trực thuộc TW'},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ['name'], 'verbose_name': 'Phường/Xã/Đặc khu', 'verbose_name_plural': 'Phường/Xã/Đặc khu'},
        ),
        migrations.AlterField(
            model_name='province',
            name='unit_type',
            field=models.CharField(choices=[('province', 'Tỉnh'), ('central_city', 'Thành phố trực thuộc TW')], default='province', max_length=20),
        ),
        migrations.AlterField(
            model_name='ward',
            name='unit_type',
            field=models.CharField(choices=[('ward', 'Phường'), ('commune', 'Xã'), ('special_zone', 'Đặc khu')], default='ward', max_length=20),
        ),
    ]
