# Generated by Django 5.0.7 on 2026-06-24 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('calendar_type', models.IntegerField(choices=[(0, 'Họp'), (1, 'Sự kiện'), (2, 'Nhắc nhở'), (3, 'Công việc')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Chờ xác nhận'), (1, 'Đã xác nhận'), (2, 'Đã hủy'), (3, 'Hoàn thành')], default=0)),
                ('department_id', models.UUIDField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Lịch',
                'verbose_name_plural': 'Lịch',
                'db_table': 'calendars',
            },
        ),
        migrations.CreateModel(
            name='CalendarJoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('status', models.IntegerField(choices=[(0, 'Chờ xác nhận'), (1, 'Chấp nhận'), (2, 'Từ chối')], default=0)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='calendars.calendar')),
            ],
            options={
                'db_table': 'calendar_joins',
                'unique_together': {('calendar', 'user_id')},
            },
        ),
    ]
