name: Auto Release Staging

on:
  push:
    branches:
      - main

concurrency:
  group: autorelease-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  auto-create-merge-migration:
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - name: Install git
        run: |
          apt-get update
          apt-get install -y git
      - uses: actions/checkout@v3
      - uses: ./.github/actions/config_git
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.DEPLOY_PAT_TOKEN }}
      - name: Cache poetry
        uses: ./.github/actions/cache_poetry
      - name: Make migration merge
        run: |
          cp .env.test .env
          poetry run python manage.py makemigrations --merge --no-input
      - run: git config --global safe.directory '*'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          token: ${{ secrets.DEPLOY_PAT_TOKEN }}
          branch: fix/auto-merge-migration
          base: main
          body: Merge migration file from github action tools
          reviewers: canh-eoh,son-eoh,phuong-eoh,nam-eoh,thinh-eoh
          title: "Auto create merge migration"
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.DEPLOY_PAT_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash

  test-all:
    runs-on: ubuntu-latest
    container: python:3.12
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
      redis:
        image: redis
    steps:
      - uses: actions/checkout@v3
        if: "!contains(github.event.head_commit.message, '[skip-unittest]')"
      - uses: ./.github/actions/test
        if: "!contains(github.event.head_commit.message, '[skip-unittest]')"
        env:
          PYTEST_ADDOPTS: -x --dist loadfile
      - name: Test API Document
        if: "!contains(github.event.head_commit.message, '[skip-unittest]')"
        run: |
          poetry run pytest root/tests/test_api_docs.py --reuse-db
        env:
          API_DOCUMENT: 1
          TEST_API: 1

  create-docker-image:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
      env:
        LD_LIBRARY_PATH: /lib
        STAGING_REGISTRY_IMAGE: ${{ secrets.STAGING_AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.STAGING_AWS_DEFAULT_REGION }}.amazonaws.com/${{ github.repository }}
        PRODUCTION_REGISTRY_IMAGE: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ github.repository }}
        COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
    services:
      docker:
        image: docker:dind
    needs:
      - test-all
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ecr
      - name: Login ECR Staging
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.STAGING_AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.STAGING_AWS_DEFAULT_REGION }}.amazonaws.com
          username: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
      - name: Build docker image staging
        run: |
          export VERSION=$(sh ./deploy/github/get_version.sh)
          echo "$VERSION"
          export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
          docker build --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg BUILD_ENV=prod --cache-from $STAGING_REGISTRY_IMAGE:base --cache-from $STAGING_REGISTRY_IMAGE:latest -t $STAGING_REGISTRY_IMAGE:$VERSION .
      - name: Push docker image staging
        run: |
          export VERSION=$(sh ./deploy/github/get_version.sh)
          echo "$VERSION"
          docker push $STAGING_REGISTRY_IMAGE:$VERSION
          docker tag $STAGING_REGISTRY_IMAGE:$VERSION $STAGING_REGISTRY_IMAGE:latest
          docker push $STAGING_REGISTRY_IMAGE:latest
      - name: Clear docker cache
        run: |
          docker system prune -f
          export VERSION=$(sh ./deploy/github/get_version.sh)
          docker image rm $STAGING_REGISTRY_IMAGE:$VERSION
          docker image rm $STAGING_REGISTRY_IMAGE:latest

  make-tag-staging:
    runs-on: ubuntu-latest
    container: python:3.9.7-slim-buster
    needs:
      - create-docker-image
    steps:
      - name: Install git
        run: |
            sed -i 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' /etc/apt/sources.list
            sed -i 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' /etc/apt/sources.list
            apt-get update
            apt-get install -y git
      - uses: actions/checkout@v3
      - uses: ./.github/actions/config_git
      - name: Set version
        id: version-release
        run: echo "version=$(bash ./deploy/github/get_version.sh)" >> $GITHUB_OUTPUT
        env:
          COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
      - uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: '${{ secrets.DEPLOY_PAT_TOKEN }}'
          tag: 's${{ steps.version-release.outputs.version }}'
