# Generated by Django 5.0.7 on 2026-06-24 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=500)),
                ('backup_type', models.IntegerField(choices=[(0, 'Tự động'), (1, 'Thủ công')], default=1)),
                ('path_type', models.IntegerField(choices=[(0, 'Lưu cục bộ'), (1, 'Lưu đám mây')], default=0)),
                ('path', models.TextField()),
                ('database_name', models.CharField(max_length=255)),
                ('server', models.CharField(blank=True, max_length=100, null=True)),
                ('size_kb', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.IntegerField(choices=[(0, 'Thành công'), (1, 'Thất bại'), (2, 'Đang thực hiện')], default=2)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nhật ký sao lưu',
                'db_table': 'backup_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=500)),
                ('path_type', models.IntegerField(default=0)),
                ('path', models.TextField()),
                ('database_name', models.CharField(max_length=255)),
                ('server', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Thành công'), (1, 'Thất bại'), (2, 'Đang thực hiện')], default=2)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('backup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.backuplog')),
            ],
            options={
                'verbose_name': 'Nhật ký phục hồi',
                'db_table': 'restore_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
