# Generated by Django 5.2.15 on 2026-07-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={
                'verbose_name': 'Mẫu biểu',
                'verbose_name_plural': 'Mẫu biểu',
            },
        ),
    ]
