# Generated by Django 5.2.15 on 2026-07-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backuplog',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Nhật ký sao lưu',
                'verbose_name_plural': 'Nhật ký sao lưu',
            },
        ),
        migrations.AlterModelOptions(
            name='restorelog',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Nhật ký phục hồi',
                'verbose_name_plural': 'Nhật ký phục hồi',
            },
        ),
    ]
