# Generated by Django 5.2.15 on 2026-07-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
            },
        ),
        migrations.AlterModelOptions(
            name='pushsubscription',
            options={
                'verbose_name': 'Đăng ký push notification',
                'verbose_name_plural': 'Đăng ký push notification',
            },
        ),
    ]
