# Generated by Django 5.2.15 on 2026-06-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Hành động', 'verbose_name_plural': 'Hành động'},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['sort_order'], 'verbose_name': 'Chức năng', 'verbose_name_plural': 'Chức năng'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Quyền hạn', 'verbose_name_plural': 'Quyền hạn'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Phân quyền người dùng', 'verbose_name_plural': 'Phân quyền người dùng'},
        ),
        migrations.AddField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='district_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='province_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
