# Generated by Codex on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_action_options_alter_function_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='department_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('role', 'department_id', 'function', 'action')},
        ),
    ]
