# Generated by Django 5.0.7 on 2026-06-24 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=500)),
                ('parent_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('department_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Thư mục',
                'db_table': 'folders',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=500)),
                ('original_name', models.CharField(max_length=500)),
                ('path', models.TextField()),
                ('size', models.BigIntegerField(default=0)),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('file_type', models.IntegerField(choices=[(0, 'Hình ảnh'), (1, 'Video'), (2, 'Âm thanh'), (3, 'Tài liệu'), (4, 'Mô hình 3D'), (5, 'Khác')], default=5)),
                ('is_private', models.BooleanField(default=False)),
                ('is_trashed', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='media_files.folder')),
            ],
            options={
                'verbose_name': 'Tệp tin',
                'db_table': 'media_files',
            },
        ),
    ]
