# Generated by Django 5.2.15 on 2026-07-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={
                'verbose_name': 'Thư mục',
                'verbose_name_plural': 'Thư mục',
            },
        ),
        migrations.AlterModelOptions(
            name='mediafile',
            options={
                'verbose_name': 'Tệp tin',
                'verbose_name_plural': 'Tệp tin',
            },
        ),
    ]
