# Generated by Django 5.0.7 on 2026-06-24 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('chat_type', models.IntegerField(choices=[(0, 'Tin nhắn riêng'), (1, 'Nhóm')], default=0)),
                ('avatar', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cuộc trò chuyện',
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('message_type', models.IntegerField(choices=[(0, 'Văn bản'), (1, 'Tệp tin'), (2, 'Hình ảnh'), (3, 'Ghi âm'), (4, 'Hệ thống')], default=0)),
                ('reply_to_id', models.UUIDField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.UUIDField()),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='chats.chat')),
            ],
            options={
                'db_table': 'chat_notes',
            },
        ),
        migrations.CreateModel(
            name='ChatVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.UUIDField()),
                ('question', models.CharField(max_length=500)),
                ('is_multiple', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='chats.chat')),
            ],
            options={
                'db_table': 'chat_votes',
            },
        ),
        migrations.CreateModel(
            name='ChatVoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='chats.chatvote')),
            ],
            options={
                'db_table': 'chat_vote_options',
            },
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('role', models.IntegerField(choices=[(0, 'Thành viên'), (1, 'Quản trị viên')], default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chats.chat')),
            ],
            options={
                'db_table': 'chat_members',
                'unique_together': {('chat', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='ChatVoteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chatvoteoption')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='chats.chatvote')),
            ],
            options={
                'db_table': 'chat_vote_results',
                'unique_together': {('vote', 'user_id', 'option')},
            },
        ),
    ]
