# Generated by Django 5.0.7 on 2026-06-24 04:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.UUIDField(db_index=True, unique=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('task_notify', models.BooleanField(default=True)),
                ('document_notify', models.BooleanField(default=True)),
                ('calendar_notify', models.BooleanField(default=True)),
                ('chat_notify', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cài đặt thông báo',
                'db_table': 'setting_notifications',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Cấu hình hệ thống',
                'db_table': 'system_configs',
            },
        ),
    ]
