# Generated by Django 5.0.7 on 2026-06-24 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Nháp'), (1, 'Đang thực hiện'), (2, 'Chờ duyệt'), (3, 'Hoàn thành'), (4, 'Đã hủy'), (5, 'Quá hạn')], db_index=True, default=0)),
                ('priority', models.IntegerField(choices=[(0, 'Thấp'), (1, 'Bình thường'), (2, 'Cao'), (3, 'Khẩn cấp')], default=1)),
                ('task_type', models.IntegerField(choices=[(0, 'Nội bộ'), (1, 'Số hóa'), (2, 'Văn bản')], default=0)),
                ('assigned_by', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Công việc',
                'verbose_name_plural': 'Công việc',
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('content', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_chats', to='tasks.task')),
            ],
            options={
                'db_table': 'task_chats',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Nháp'), (1, 'Chờ duyệt'), (2, 'Đã duyệt'), (3, 'Từ chối')], default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_documents', to='tasks.task')),
            ],
            options={
                'db_table': 'task_documents',
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('action', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('performed_by', models.UUIDField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='tasks.task')),
            ],
            options={
                'db_table': 'task_histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('role', models.IntegerField(choices=[(0, 'Người thực hiện'), (1, 'Người duyệt'), (2, 'Người theo dõi')], default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_users', to='tasks.task')),
            ],
            options={
                'db_table': 'task_users',
            },
        ),
    ]
