# Generated by Codex on 2026-06-26

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('authentication', '0003_permission_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_assign_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_receive_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_see_department_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_vice_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['level', 'name'], 'verbose_name': 'Vai trò', 'verbose_name_plural': 'Vai trò'},
        ),
        migrations.CreateModel(
            name='RoleDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_departments', to='departments.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_departments', to='authentication.role')),
            ],
            options={
                'verbose_name': 'Vai trò theo phòng ban',
                'verbose_name_plural': 'Vai trò theo phòng ban',
                'db_table': 'roles_department',
                'unique_together': {('role', 'department')},
            },
        ),
    ]