"""
Django settings for root project.
Generated by 'django-admin startproject' using Django 2.2.5.
For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import environ
import logging
import os
import sentry_sdk
import sys
from celery.schedules import crontab
from corsheaders.defaults import default_headers
from datetime import timedelta
from django.utils.translation import gettext_lazy as _
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
from sentry_sdk.integrations.redis import RedisIntegration
from sentry_sdk.integrations.tornado import TornadoIntegration

# https://github.com/joke2k/django-environ
env = environ.Env(
    DEBUG=(bool, False),
    LOGGING_LEVEL=(str, 'INFO'),
    SECRET_KEY=(str, '33d#&1-)0cus@w(p@h^)&*xw)r4sr+hzo2*)l$zyvc+jxl00#3'),
    EMAIL_BACKEND=(str, 'django.core.mail.backends.smtp.EmailBackend'),
    CELERY_EMAIL_BACKEND=(str, 'sendgrid_backend.SendgridBackend'),
    CELERY_TASK_ALWAYS_EAGER=(bool, False),
    CELERY_WORKER_CONCURRENCY=(int, 1),
    CELERY_WORKER_MAX_TASKS_PER_CHILD=(int, 1000),
    CELERY_RESULT_BACKEND=(str, ''),
    EMAIL_HOST=(str, 'smtp.gmail.com'),
    EMAIL_HOST_USER=(str, ''),
    EMAIL_HOST_PASSWORD=(str, ''),
    EMAIL_PORT=(int, 587),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_USE_SSL=(bool, False),
    EMAIL_TLS_VERIFY=(bool, True),
    EMAIL_SENDER=(str, ''),
    EMAIL_SERVICE=(str, 'device.service@eoh.io'),
    ERA_HOME_PAGE=(str, 'https://app.e-ra.io/'),
    ERA_RETURN_URL=(str, 'https://app.e-ra.io/processing'),
    SENDGRID_API_KEY=(str, ''),
    SENDGRID_SANDBOX_MODE_IN_DEBUG=(bool, False),
    DEFAULT_FILE_STORAGE=(str, 'django.core.files.storage.FileSystemStorage'),
    MEDIA_ROOT=(str, ''),
    MEDIA_URL=(str, '/media/'),
    AWS_S3_CUSTOM_DOMAIN=(str, ''),
    AWS_STORAGE_BUCKET_NAME=(str, 'aws'),
    AWS_BUCKET_PATH_CODEGEN=(str, 'tmp_codegen'),
    CORS_ORIGIN_ALLOW_ALL=(bool, False),
    SITE_ID=(int, 1),
    ROOT_URLCONF=(str, 'root.urls'),
    REDIS_URL=(str, 'redis://redis:6379/2'),
    DB_CONN_MAX_AGE=(int, 60),
    ALLOW_HEADERS_LIST=(str, ''),
    CSRF_TRUSTED_ORIGINS=(str, ''),

    THROTTLE_RATES_ANON=(str, '3000/hour'),
    THROTTLE_RATES_USER=(str, '3000/hour'),
    THROTTLE_RATES_USER_SEND_OTP=(str, '1/minute'),
    THROTTLE_RATES_USER_REGISTER=(str, '100/minute'),
    THROTTLE_RATES_USER_VERIFY_OTP=(str, '100/day'),
    PHONE_VERIFICATION_TIMEOUT=(int, 60),
    ACCOUNT_DEFAULT_HTTP_PROTOCOL=(str, 'http'),
    SIMPLE_JWT_ACCESS_TOKEN_LIFETIME_MINUTES=(int, 15),
    SIMPLE_JWT_REFRESH_TOKEN_LIFETIME_DAYS=(int, 7),
    SIMPLE_JWT_ROTATE_REFRESH_TOKENS=(bool, True),
    SIMPLE_JWT_BLACKLIST_AFTER_ROTATION=(bool, True),

    GOOGLE_MAP_API_KEY=(str, ''),
    LOGIN_REDIRECT_URL=(str, '/'),

    SMS_API_KEY=(str, ''),
    SMS_SECRET_KEY=(str, ''),
    SMS_OPT_TIMEOUT=(int, 60),  # seconds
    HASH_CODE_AUTO_FILL_SMS=(str, '%!@GV$'),

    SENTRY_IGNORE_ERRORS=(str, ''),
    SENTRY_DSN=(str, 'SENTRY_DSN'),

    PRIMARY_SITE_URL=(str, 'https://staging-app.gladiusart.com'),
    WEB_PUSH_VAPID_PUBLIC_KEY=(str, 'BPIOcoYd-_gZkDmTDHyJ9XHPCR0UtGxC9136JSHr5A7HyRkvRXQBGJCbQjCMd0argkzolL_cZJ_bl_uTxoNVGgw'),
    WEB_PUSH_VAPID_PRIVATE_KEY=(str, 'x02uQX2QAsrEMEBdXm3NGhag2i9z1vDIIJhoNVbtRhM'),
    WEB_PUSH_VAPID_SUBJECT=(str, ''),
    PUSH_NOTIFICATION_ICON_URL=(str, ''),
    FRONTEND_URL=(str, 'http://localhost:3000'),
    CDN_BASE_URL=(str, 'https://trungtambaoton-cloud.hongvan.net'),
    CDN_API_URL=(str, 'https://trungtambaoton-cloud.hongvan.net/api'),
    ONLYOFFICE_SERVER_URL=(str, 'https://onlyoffice.hongvan.net'),
    ONLYOFFICE_JWT_TOKEN=(str, ''),
    WEB_PUSH_PUBLIC_KEY=(str, ''),
    WEB_PUSH_PRIVATE_KEY=(str, ''),
)

IS_TEST = 'test' in sys.argv or 'pytest' in sys.argv[0] or os.getenv('IS_TEST')
if IS_TEST:
    os.environ.setdefault('IS_TEST', '1')
# Load .env.local for runserver and any manage.py command (migrate, createsuperuser, shell, …)
IS_LOCAL = (
    'runserver' in sys.argv
    or 'runserver_plus' in sys.argv
    or any('daphne' in arg for arg in sys.argv)
    or (sys.argv and os.path.basename(sys.argv[0]) == 'manage.py')
)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
root = environ.Path(__file__) - 2  # 2 level above
# BASE_DIR = root()
BASE_DIR = root()

if IS_TEST:
    environ.Env.read_env(os.path.join(BASE_DIR, '.env.test'))

if IS_LOCAL:
    environ.Env.read_env(os.path.join(BASE_DIR, '.env.local'))

if not IS_TEST:
    env_files = ['.env', '/config/.env']
    for env_file in env_files:
        if os.path.isfile(env_file):
            environ.Env.read_env(env_file)

LOGOUT_REDIRECT_URL = '/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')
IS_PRODUCTION = False


def split_csv(value):
    return [item.strip() for item in value.split(',') if item.strip()]


LOCAL_DEV_ORIGINS = [
    'http://localhost:3000',
    'https://localhost:3000',
    'http://127.0.0.1:3000',
    'https://127.0.0.1:3000',
    'http://0.0.0.0:3000',
    'https://0.0.0.0:3000',
    'http://localhost:3001',
    'https://localhost:3001',
    'http://127.0.0.1:3001',
    'https://127.0.0.1:3001',
]

LOCAL_DEV_HOSTS = [
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    '[::1]',
    '::1',
]

ALLOWED_HOSTS_CONFIG = env('ALLOWED_HOSTS')  # type: str
if ALLOWED_HOSTS_CONFIG:
    ALLOWED_HOSTS = split_csv(ALLOWED_HOSTS_CONFIG)
else:
    ALLOWED_HOSTS = []

if IS_LOCAL or DEBUG:
    ALLOWED_HOSTS.extend(LOCAL_DEV_HOSTS)
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))

# Trust X-Forwarded-Proto từ nginx reverse proxy → request.build_absolute_uri() trả https://
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

CSRF_TRUSTED_ORIGINS = split_csv(env('CSRF_TRUSTED_ORIGINS'))
if IS_LOCAL or DEBUG:
    CSRF_TRUSTED_ORIGINS.extend(LOCAL_DEV_ORIGINS)
    CSRF_TRUSTED_ORIGINS.extend([
        'https://*.ngrok-free.dev',
        'https://*.ngrok.app',
        'https://*.ngrok.io',
    ])
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.postgres',

    'corsheaders',
    'djcelery_email',
    'django_extensions',
    'channels',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_yasg',
    'django_celery_beat',
    'green_migration',

    # Business applications migrated from the current backend. Keep these
    # under the core namespace while preserving app labels and migrations.
    'core.authentication',
    'core.accounts',
    'core.departments',
    'core.tasks',
    'core.documents',
    'core.archives',
    'core.calendars.apps.CalendarsConfig',
    'core.chats.apps.ChatsConfig',
    'core.chat_notes.apps.ChatNotesConfig',
    'core.chat_votes.apps.ChatVotesConfig',
    'core.chat_reminds.apps.ChatRemindsConfig',
    'core.media_files',
    'core.ratings',
    'core.monuments',
    'core.templates_app',
    'core.notifications',
    'core.settings_app',
    'core.backup',

    'common',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if not IS_TEST:  # setup debug toolbar
    INSTALLED_APPS += ['debug_toolbar']
    index = MIDDLEWARE.index('corsheaders.middleware.CorsMiddleware')
    DEBUG_MIDDLEWARE = [
        'debug_toolbar.middleware.DebugToolbarMiddleware',
        'common.middleware.wrap_json_for_debug_toolbar',
    ]
    MIDDLEWARE = MIDDLEWARE[:index] + DEBUG_MIDDLEWARE + MIDDLEWARE[index:]
    # https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#debug-toolbar-config
    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': 'common.utils.debug_toolbar.show_toolbar',
    }
    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.history.HistoryPanel',
        'debug_toolbar.panels.versions.VersionsPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        # 'debug_toolbar.panels.cache.CachePanel',  # debug toolbar version 4.0 has issue with cache panel
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
        'debug_toolbar.panels.profiling.ProfilingPanel',
    ]

ROOT_URLCONF = env('ROOT_URLCONF')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'root.wsgi.application'
ASGI_APPLICATION = 'root.asgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES = {
    'default': env.db(),
}
# https://docs.djangoproject.com/en/3.1/ref/settings/#conn-max-age
DB_CONN_MAX_AGE = env('DB_CONN_MAX_AGE')

DATABASES['default']['CONN_MAX_AGE'] = DB_CONN_MAX_AGE

# https://docs.djangoproject.com/en/2.0/ref/settings/#caches
CACHES = {
    'default': {
        **env.cache(),
        'BACKEND': 'django_redis.cache.RedisCache',
    },
}

REDIS_URL = env('REDIS_URL')
if IS_TEST:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }

# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-user-model
AUTH_USER_MODEL = 'authentication.User'
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
]

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = root('static')
STATIC_URL = '/static/'
STATICFILES_DIRS = tuple(
    static_dir
    for static_dir in (root('staticfiles'),)
    if os.path.isdir(static_dir)
)
MEDIA_ROOT = env('MEDIA_ROOT') or root('media')
MEDIA_URL = env('MEDIA_URL')

# https://github.com/pmclanahan/django-celery-email
EMAIL_BACKEND = env('EMAIL_BACKEND')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')
EMAIL_TLS_VERIFY = env('EMAIL_TLS_VERIFY')
if 'EMAIL_URL' in os.environ:
    vars().update(env.email(backend=EMAIL_BACKEND))
else:
    EMAIL_HOST = env('EMAIL_HOST')
    EMAIL_HOST_USER = env('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
    EMAIL_PORT = env('EMAIL_PORT')
    EMAIL_USE_TLS = env('EMAIL_USE_TLS')
    EMAIL_USE_SSL = env('EMAIL_USE_SSL')

# https://github.com/sklarsa/django-sendgrid-v5
SENDGRID_API_KEY = env('SENDGRID_API_KEY')
SENDGRID_SANDBOX_MODE_IN_DEBUG = env('SENDGRID_SANDBOX_MODE_IN_DEBUG')
CELERY_EMAIL_BACKEND = env('CELERY_EMAIL_BACKEND')
EMAIL_SENDER = env('EMAIL_SENDER')
EMAIL_SERVICE = env('EMAIL_SERVICE')
CELERY_EMAIL_TASK_CONFIG = {
    'queue': 'email',
}

# https://docs.sentry.io/platforms/python/django/?_ga=2.23805178.1591677347.1539400796-2037531365.1522374040
SentryErrorLogging = LoggingIntegration(
    level=logging.ERROR,
    event_level=logging.ERROR,
)

if env('SENTRY_DSN'):
    IGNORE_ERRORS = []
    if env('SENTRY_IGNORE_ERRORS'):
        IGNORE_ERRORS = env('SENTRY_IGNORE_ERRORS').split(',')  # type: list
        IGNORE_ERRORS = list(filter(lambda x: (x != ''), IGNORE_ERRORS))


    def before_send(event, hint):
        if 'exc_info' in hint:
            exc_type, exc_value, tb = hint['exc_info']
            if IGNORE_ERRORS and exc_value.args[0].startswith(tuple(IGNORE_ERRORS)):
                return None
        elif 'log_record' in hint:
            if IGNORE_ERRORS and hint['log_record'].msg.startswith(tuple(IGNORE_ERRORS)):
                return None
        return event


    sentry_sdk.init(
        dsn=env('SENTRY_DSN'),
        before_send=before_send,
        environment=env('ENVIRONMENT'),
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            RedisIntegration(),
            TornadoIntegration(),
            SentryErrorLogging,
        ],
    )

# https://github.com/ottoyiu/django-cors-headers
CORS_ORIGIN_WHITELIST_STR = env('CORS_ORIGIN_WHITELIST')  # type: str
CORS_ORIGIN_WHITELIST = split_csv(CORS_ORIGIN_WHITELIST_STR)
if IS_LOCAL or DEBUG:
    CORS_ORIGIN_WHITELIST.extend(LOCAL_DEV_ORIGINS)
CORS_ORIGIN_WHITELIST = list(dict.fromkeys(CORS_ORIGIN_WHITELIST))
CORS_ALLOWED_ORIGINS = CORS_ORIGIN_WHITELIST
CORS_ORIGIN_ALLOW_ALL = env('CORS_ORIGIN_ALLOW_ALL')
# django-cors-headers 4.x uses this spelling; retain the production env key.
CORS_ALLOW_ALL_ORIGINS = CORS_ORIGIN_ALLOW_ALL

CORS_ALLOW_HEADERS = list(default_headers)
CORS_ALLOW_HEADERS += [
    'content-range',
]
CORS_EXPOSE_HEADERS = [
    'file-size',
    'content-range',
    'content-disposition',
]
ALLOW_HEADERS_LIST = env('ALLOW_HEADERS_LIST')
if ALLOW_HEADERS_LIST:
    CORS_ALLOW_HEADERS += ALLOW_HEADERS_LIST.split(',')

# http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html
# https://docs.celeryq.dev/en/3.1/configuration.html
CELERY_BROKER_URL = env('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND')
CELERY_TASK_ALWAYS_EAGER = env('CELERY_TASK_ALWAYS_EAGER') or IS_TEST
CELERY_TASK_EAGER_PROPAGATES = CELERY_TASK_ALWAYS_EAGER
CELERY_WORKER_MAX_TASKS_PER_CHILD = env('CELERY_WORKER_MAX_TASKS_PER_CHILD')
CELERY_BEAT_SCHEDULE = {}  # to use this setting, you need to enable beat.temp.yaml deployment, by rename to beat.yaml
CELERY_WORKER_CONCURRENCY = env('CELERY_WORKER_CONCURRENCY')
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

INTERNAL_IPS = env('INTERNAL_IPS').split(',')  # type: list

THROTTLE_RATES_ANON = env('THROTTLE_RATES_ANON')
THROTTLE_RATES_USER = env('THROTTLE_RATES_USER')
THROTTLE_RATES_USER_VERIFY_OTP = env('THROTTLE_RATES_USER_VERIFY_OTP')
THROTTLE_RATES_USER_SEND_OTP = env('THROTTLE_RATES_USER_SEND_OTP')
THROTTLE_RATES_USER_REGISTER = env('THROTTLE_RATES_USER_REGISTER')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.StandardPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
}

if 'ACCESS_TOKEN_LIFETIME_DAYS' in os.environ:
    ACCESS_TOKEN_LIFETIME = timedelta(days=env.int('ACCESS_TOKEN_LIFETIME_DAYS'))
else:
    ACCESS_TOKEN_LIFETIME = timedelta(minutes=env('SIMPLE_JWT_ACCESS_TOKEN_LIFETIME_MINUTES'))

if 'REFRESH_TOKEN_LIFETIME_DAYS' in os.environ:
    REFRESH_TOKEN_LIFETIME = timedelta(days=env.int('REFRESH_TOKEN_LIFETIME_DAYS'))
else:
    REFRESH_TOKEN_LIFETIME = timedelta(days=env('SIMPLE_JWT_REFRESH_TOKEN_LIFETIME_DAYS'))

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': ACCESS_TOKEN_LIFETIME,
    'REFRESH_TOKEN_LIFETIME': REFRESH_TOKEN_LIFETIME,
    'ROTATE_REFRESH_TOKENS': env('SIMPLE_JWT_ROTATE_REFRESH_TOKENS'),
    'BLACKLIST_AFTER_ROTATION': env('SIMPLE_JWT_BLACKLIST_AFTER_ROTATION'),
    'UPDATE_LAST_LOGIN': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'SIGNING_KEY': SECRET_KEY,
}

AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
FILE_STORAGE_BACKEND = env('DEFAULT_FILE_STORAGE')
if IS_TEST:
    FILE_STORAGE_BACKEND = 'django.core.files.storage.FileSystemStorage'
STORAGES = {
    'default': {
        'BACKEND': FILE_STORAGE_BACKEND,
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

AWS_DEFAULT_ACL = 'public-read'
AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN')
AWS_S3_FILE_OVERWRITE = False
AWS_BUCKET_PATH_CODEGEN = env('AWS_BUCKET_PATH_CODEGEN')

LOCATION_FIELD_PATH = STATIC_URL + 'location_field'
LOCATION_FIELD = {
    'map.provider': 'google',
    'map.zoom': 13,

    'search.provider': 'google',
    'search.suffix': '',

    # Google
    'provider.google.api': '//maps.google.com/maps/api/js?sensor=false',
    'provider.google.api_key': env('GOOGLE_MAP_API_KEY'),
    'provider.google.api_libraries': '',
    'provider.google.map.type': 'ROADMAP',

    # Mapbox
    'provider.mapbox.access_token': '',
    'provider.mapbox.max_zoom': 18,
    'provider.mapbox.id': 'mapbox.streets',

    # OpenStreetMap
    'provider.openstreetmap.max_zoom': 18,

    # misc
    'resources.root_path': LOCATION_FIELD_PATH,
    'resources.media': {
        'js': (
            LOCATION_FIELD_PATH + '/js/form.js',
        ),
    },
}

SWAGGER_SETTINGS = {
    'DEFAULT_PAGINATOR_INSPECTORS': [
        'drf_yasg.inspectors.DjangoRestResponsePagination',
        'drf_yasg.inspectors.CoreAPICompatInspector',
    ],
    'SECURITY_DEFINITIONS': {
        'Token': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
        },
    },
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

# ADMIN_URL
SITE_ID = env('SITE_ID')

LOGGING_LEVEL = env('LOGGING_LEVEL') if not IS_TEST else 'ERROR'
# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {module} {message}',
            'style': '{',
            'datefmt': '%y %b %d, %H:%M:%S',
        },
        'datadog': {
            'format': '{levelname} Datadog {asctime} {message}',
            'style': '{',
            'datefmt': '%d/%m/%Y %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'datadog': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'datadog',
        },
    },
    'loggers': {
        'celery': {
            'handlers': ['console'],
            'level': LOGGING_LEVEL,
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'datadog': {
            'handlers': ['datadog'],
            'level': 'INFO',
            'propagate': False,
        },
        '': {
            'handlers': ['console'],
            'level': LOGGING_LEVEL,
            'propagate': False,
        },
    },
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = env('LOGIN_REDIRECT_URL')

# ESMS SERVICE
SMS_API_KEY = env('SMS_API_KEY')
SMS_SECRET_KEY = env('SMS_SECRET_KEY')
SMS_OPT_TIMEOUT = env('SMS_OPT_TIMEOUT')
HASH_CODE_AUTO_FILL_SMS = env('HASH_CODE_AUTO_FILL_SMS')

# AI XÓA PHÔNG NỀN (remove.bg → Photoroom → rembg local)
REMOVEBG_API_KEY = env('REMOVEBG_API_KEY', default='')
PHOTOROOM_API_KEY = env('PHOTOROOM_API_KEY', default='')

PHONE_VERIFICATION_TIMEOUT = env('PHONE_VERIFICATION_TIMEOUT')

LANGUAGES = [
    ('vi', _('Vietnamese')),
    ('en', _('English')),
]
LOCALE_PATHS = (
    os.path.join(BASE_DIR, "locale"),
)

DEBUG_HEADER = env('DEBUG_HEADER')

# accounts
ENABLED_FEATURES = {
    'smart_parking',
}

# deploy info
VERSION = env('VERSION')
ENVIRONMENT = env('ENVIRONMENT')
PROJECT_SLUG = env('PROJECT_SLUG')
DOCKER_IMAGE = env('DOCKER_IMAGE')
PRIMARY_SITE_URL = env('PRIMARY_SITE_URL')
WEB_PUSH_VAPID_PUBLIC_KEY = env('WEB_PUSH_VAPID_PUBLIC_KEY')
WEB_PUSH_VAPID_PRIVATE_KEY = env('WEB_PUSH_VAPID_PRIVATE_KEY')
WEB_PUSH_VAPID_SUBJECT = env('WEB_PUSH_VAPID_SUBJECT') or PRIMARY_SITE_URL
PUSH_NOTIFICATION_ICON_URL = env('PUSH_NOTIFICATION_ICON_URL') or f'{PRIMARY_SITE_URL.rstrip("/")}/icon-192.png'

# Environment-backed integration settings used by the migrated applications.
FRONTEND_URL = env('FRONTEND_URL')
CDN_BASE_URL = env('CDN_BASE_URL')
CDN_API_URL = env('CDN_API_URL')
ONLYOFFICE_SERVER_URL = env('ONLYOFFICE_SERVER_URL')
ONLYOFFICE_JWT_TOKEN = env('ONLYOFFICE_JWT_TOKEN')
WEB_PUSH_PUBLIC_KEY = env('WEB_PUSH_PUBLIC_KEY')
WEB_PUSH_PRIVATE_KEY = env('WEB_PUSH_PRIVATE_KEY')

if 'EMAIL_HOST' in os.environ:
    EMAIL_HOST = env('EMAIL_HOST')
if 'EMAIL_HOST_USER' in os.environ:
    EMAIL_HOST_USER = env('EMAIL_HOST_USER')
if 'EMAIL_HOST_PASSWORD' in os.environ:
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
if 'EMAIL_PORT' in os.environ:
    EMAIL_PORT = env('EMAIL_PORT')
if 'EMAIL_USE_TLS' in os.environ:
    EMAIL_USE_TLS = env('EMAIL_USE_TLS')
if 'EMAIL_USE_SSL' in os.environ:
    EMAIL_USE_SSL = env('EMAIL_USE_SSL')
AWS_QUERYSTRING_AUTH = False
