# Generated by Django 5.0.7 on 2026-06-24 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=500)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('document_type', models.IntegerField(choices=[(0, 'Văn bản đến'), (1, 'Văn bản đi'), (2, 'Văn bản nội bộ')], db_index=True, default=2)),
                ('status', models.IntegerField(choices=[(0, 'Nháp'), (1, 'Chờ duyệt'), (2, 'Đã duyệt'), (3, 'Từ chối'), (4, 'Đã ban hành'), (5, 'Lưu trữ')], db_index=True, default=0)),
                ('content', models.TextField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('department_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('urgency_level', models.IntegerField(default=0)),
                ('security_level', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Văn bản',
                'verbose_name_plural': 'Văn bản',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('file_path', models.TextField()),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.document')),
            ],
            options={
                'db_table': 'document_files',
            },
        ),
    ]
