# Generated by Django 5.2.15 on 2026-07-07 07:54

import apps.monuments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monumentfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=apps.monuments.models.monument_upload_to),
        ),
        migrations.AlterField(
            model_name='monumentsection',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.monuments.models.monument_section_upload_to),
        ),
    ]
