# Generated by Codex on 2026-06-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clean_staff_user_refs(apps, schema_editor):
    Staff = apps.get_model('departments', 'Staff')
    User = apps.get_model('authentication', 'User')
    valid_users = {str(v) for v in User.objects.values_list('id', flat=True)}
    for staff in Staff.objects.all():
        if staff.user_id and str(staff.user_id) not in valid_users:
            staff.user_id = None
            staff.save(update_fields=['user_id'])


def sync_staff_profiles(apps, schema_editor):
    Staff = apps.get_model('departments', 'Staff')
    User = apps.get_model('authentication', 'User')
    Department = apps.get_model('departments', 'Department')
    Province = apps.get_model('accounts', 'Province')
    District = apps.get_model('accounts', 'District')

    valid_departments = {str(v) for v in Department.objects.values_list('id', flat=True)}
    valid_provinces = {str(v) for v in Province.objects.values_list('id', flat=True)}
    valid_districts = {str(v) for v in District.objects.values_list('id', flat=True)}

    for user in User.objects.filter(is_deleted=False):
        staff = Staff.objects.filter(user_id=user.id, is_deleted=False).first()
        created = False
        if not staff:
            staff = Staff(user_id=user.id)
            created = True

        if not staff.first_name:
            staff.first_name = user.first_name or ''
        if not staff.last_name:
            staff.last_name = user.last_name or ''
        if not staff.email:
            staff.email = user.email or ''
        if not staff.phone_number:
            staff.phone_number = user.phone or ''
        if not staff.address:
            staff.address = user.address or ''
        if not staff.avatar:
            staff.avatar = user.avatar or ''

        if not staff.department_id and user.department_id and str(user.department_id) in valid_departments:
            staff.department_id = user.department_id
        if not staff.province_id and user.province_id and str(user.province_id) in valid_provinces:
            staff.province_id = user.province_id
        if not staff.district_id and user.district_id and str(user.district_id) in valid_districts:
            staff.district_id = user.district_id

        if created:
            staff.save()
        else:
            staff.save(update_fields=[
                'first_name', 'last_name', 'email', 'phone_number', 'address', 'avatar',
                'department', 'province', 'district', 'updated_at',
            ])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_185_reference_schema'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_poad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(clean_staff_user_refs, migrations.RunPython.noop),
        migrations.RenameField(
            model_name='staff',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='departments.department'),
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='avatar',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='accounts.province'),
        ),
        migrations.AddField(
            model_name='staff',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='accounts.district'),
        ),
        migrations.AddField(
            model_name='staff',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='accounts.ward'),
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='sign',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='stamp',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='sign_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='stamp_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='email_personal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),

        migrations.RunPython(sync_staff_profiles, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Phòng ban', 'verbose_name_plural': 'Phòng ban'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Nhân sự', 'verbose_name_plural': 'Nhân sự'},
        ),
    ]