# Generated by Django 5.2.15 on 2026-07-01 08:58

import core.monuments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=500)),
                ('recognition_decision', models.CharField(max_length=500)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('year_of_construction', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=500)),
                ('type_of_monument', models.IntegerField(choices=[(0, 'Cấp quốc gia đặc biệt'), (1, 'Cấp quốc gia'), (2, 'Cấp thành phố')], default=0)),
                ('priority_mode', models.IntegerField(choices=[(0, 'Luôn ưu tiên'), (1, 'Xuất hiện theo ngày đăng'), (2, 'Ẩn')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Soạn thảo'), (1, 'Chờ duyệt'), (2, 'Đã duyệt'), (3, 'Không duyệt'), (4, 'Trả lại'), (5, 'Đã xuất bản')], db_index=True, default=0)),
                ('type', models.IntegerField(choices=[(0, 'Công khai'), (1, 'Không công khai')], default=0)),
                ('pending_level', models.IntegerField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monuments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ di tích',
                'verbose_name_plural': 'Hồ sơ di tích',
                'db_table': 'monuments',
            },
        ),
        migrations.CreateModel(
            name='MonumentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('file', models.FileField(upload_to=core.monuments.models.monument_upload_to)),
                ('file_name', models.CharField(max_length=500)),
                ('size', models.BigIntegerField(default=0)),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Hình ảnh'), (1, 'Âm thanh'), (2, 'Video'), (3, 'Tài liệu'), (4, 'Mô hình 3D'), (5, 'Khác')], default=5)),
                ('mode', models.IntegerField(choices=[(0, 'Hình đại diện'), (1, 'Hình đại diện không công khai'), (2, 'Hình ảnh hiện vật'), (3, 'Hình ảnh chi tiết'), (4, 'Video'), (5, 'Định dạng 3D'), (6, 'Kiến trúc'), (7, 'Hình ảnh bản vẽ kỹ thuật'), (8, 'Bản đồ khoanh vùng'), (9, 'Quyết định công nhận'), (10, 'Xếp hạng')])),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='monuments.monument')),
            ],
            options={
                'verbose_name': 'Tệp hồ sơ di tích',
                'verbose_name_plural': 'Tệp hồ sơ di tích',
                'db_table': 'monument_files',
            },
        ),
        migrations.CreateModel(
            name='MonumentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('requested_date', models.DateTimeField(blank=True, null=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Trình duyệt'), (1, 'Duyệt'), (2, 'Không duyệt'), (3, 'Trả lại'), (4, 'Đẩy lên website')], default=0)),
                ('level', models.IntegerField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monument_history_confirms', to=settings.AUTH_USER_MODEL)),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='monuments.monument')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monument_history_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử hồ sơ di tích',
                'verbose_name_plural': 'Lịch sử hồ sơ di tích',
                'db_table': 'monument_histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonumentSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, '1 Đối tượng: Hình ảnh'), (1, '2 Đối tượng: Hình ảnh - Đoạn văn'), (2, '1 Đối tượng: Đoạn văn'), (3, '2 Đối tượng: Đoạn văn - Hình ảnh')], default=0)),
                ('order', models.IntegerField(default=1)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.monuments.models.monument_section_upload_to)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_extension', models.CharField(blank=True, max_length=20, null=True)),
                ('file_type', models.IntegerField(blank=True, null=True)),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='monuments.monument')),
            ],
            options={
                'verbose_name': 'Nội dung di tích',
                'verbose_name_plural': 'Nội dung di tích',
                'db_table': 'monument_sections',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
