# Generated by Django 5.0.7 on 2026-06-24 04:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_type', models.IntegerField(choices=[(0, 'Mẫu văn bản'), (1, 'Biểu mẫu'), (2, 'Xử lý văn bản')], default=0)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('department_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mẫu biểu',
                'db_table': 'templates',
            },
        ),
    ]
